#!/bin/bash
if [ -e goatconfig.json ]
then
    echo "Goat: Creating config"
    touch goatconfig.json
    echo "config created!" >> goatconfig.json
else
    echo "goat v0.1.0"
fi 
python3 install.py $1 $2 $3